### ISSUE TITLE
[Enhancement] Support static linkage of Beef code into binaries compiled outside of Beef IDE

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1087]
In order to permit Beef to be used in a broader toolchain, it must be possible for Beef code to be linked statically into another binary. At the moment, the only supported way to run Beef code in another application is via dynamic linkage. Otherwise, the binary must be compiled using the Beef IDE.

- Beef Compiler must be able to generate complete object code in a static build context
- Beef Compiler static output must be a valid and linkable
- Unused portions of corlib should not cause missing symbols

Static object or library builds should work cross-platform. Ultimately, the Beef Compiler should be able to output a valid, reusable Static Library per platform.

I have created a repository for validating this use case: https://github.com/hunterbridges/BeefStaticLibTest

Let me know if you need any more info!

**Comment by bfiete** [comment]
Fixed at b7750583930e00c58037ba0dec3c4b54e1132dc8

For the invalid file issue- the problem was that `BeefLibrary__.lib` was actually empty, and the linker choked on that.

For the `System.Random` linking issues - I believe this was from linking `*.obj`. Beef won't remove old unused object files from the build directory - the Beef build process directly supplies the used object files to the linker so that's not a problem for it. Even if you don't have any old object files, it's possible (but rare) for object files to be created but then later be determined to be unnecessary even with a clean compilation.

So now for `Static Lib`, there will just be a single `BeefLibrary.lib` that includes all required Beef object files (including vdata, corlib files, other referenced libraries), so you just need to link to that and the Beef runtime and you're good to go.

Reopen this item if there area any other issues.

**Comment by hunterbridges** [comment]
Gave the new static lib build a whirl... I think there may be another issue with spaces in paths:

```
Compiling...
Beef compilation time: 1.33s
752 modules built, 753 object files generated
Executing: "C:\\Program Files\\BeefLang\\bin\\llvm\\bin\\llvm-ar.exe" -M
C:\\Program Files\\BeefLang\\bin\\llvm\\bin\llvm-ar.exe: error: "C:\Users\Hunter: invalid argument.

OVERVIEW: LLVM Archiver

USAGE: llvm-ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       llvm-ar -M [<mri-script]

(Shows all the llvm-ar help...)

Execution time: 0.03s
Execution Failed
ERROR: BUILD FAILED
Total build time: 1.49s
```

For reference, all of my repos (except my clone of Beef) are under my user folder in `C:\Users\Hunter Bridges\Projects`, so if there's a path escape issue anywhere (spaces aren't quoted or escaped), it usually reveals itself by failing on that same `C:\Users\Hunter` path (which doesn't exist)

**Comment by bfiete** [comment]
I do believe 23dafd4e6db8398c018b22a37a07c333a422a25e should fix this.

**Comment by hunterbridges** [comment]
Tried again after latest update. It's very close to working, however I am still missing 4 symbols, specifically ones around the handshake with our Beef-based game logic. `RSDK_InitBeefLogic` and `RegisterDLLTypes` are functions we have marked as Export. `BeefStart` and `BeefStop` are the start/stop procs you had mentioned in Discord

```
2>ProjectYo Win32.cpp
2>   Creating library C:\Users\Hunter Bridges\Projects\Project Yo\ProjectYo\EXE\ProjectYo Win32.lib and object C:\Users\Hunter Bridges\Projects\Project Yo\ProjectYo\EXE\ProjectYo Win32.exp
2>ProjectYo Win32.obj : error LNK2019: unresolved external symbol BeefStart referenced in function "bool __cdecl RSDK::Init(void)" (?Init@RSDK@@YA_NXZ)
2>ProjectYo Win32.obj : error LNK2019: unresolved external symbol BeefStop referenced in function "void __cdecl RSDK::Shutdown(void)" (?Shutdown@RSDK@@YAXXZ)
2>ProjectYo Win32.obj : error LNK2019: unresolved external symbol RSDK_InitBeefLogic referenced in function "bool __cdecl RSDK::Init(void)" (?Init@RSDK@@YA_NXZ)
2>ProjectYo Win32.obj : error LNK2019: unresolved external symbol RegisterDLLTypes referenced in function "bool __cdecl RSDK::Init(void)" (?Init@RSDK@@YA_NXZ)
2>C:\Users\Hunter Bridges\Projects\Project Yo\ProjectYo\EXE\ProjectYo Win32.exe : fatal error LNK1120: 4 unresolved externals
2>Done building project "ProjectYo Win32.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by hunterbridges** [comment]
False alarm, links successfully if I use `/WHOLEARCHIVE`

**Comment by bfiete** [comment]
Hm. That shouldn't have been necessary. It wasn't necessary in my tests...
