### ISSUE TITLE
false data cycle report on sized arrays

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1191]
when buliding this clean, then uncommenting the new members of Body, and attempting to compile again, it will claim that Collection.A causes a data cycle

```
	class Program
	{
		public static void Main()
		{
			Collection d;		
			Body a;
		}
	}

	struct Body
	{
		public int d;
		public int* f;
		/*public int* a;
		public int* e;
		public int* n;*/
	}

	enum Collection
	{
		case A(Body[11] b, int x);
		case b(uint8[11] d, int x, int y);
	}
```

**Comment by disarray2077** [comment]
I don't know if this is related, but I also got a completely nonsense data-cycle error in a enum, but this one isn't a union:
![image](https://user-images.githubusercontent.com/86157825/139554190-b31d995d-4b33-4470-8c98-95613f0090b4.png)

**Comment by EinScott** [comment]
hm.. maybe it's about sized arrays?
cleaning also fixes it for you, right?

**Comment by disarray2077** [comment]
> cleaning also fixes it for you, right?

Yes

**Comment by bfiete** [comment]
Fixed at 9697c2a682254ad9146bbb127b20724bb7261856

**Comment by disarray2077** [comment]
My issue was different after all, it is still happening, but I managed to create a repro code so I will create another issue for it.
