### ISSUE TITLE
Enum equality check calls explicit type cast operator

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1391]
In the example below I have two different enums: `MyEnum` and `MyOtherEnum`. `MyOtherEnum` has an explicit type cast to `MyEnum`.

Now when I try to compare two values of type `MyOtherEnum` the explicit cast to `MyEnum` will be performed for both values and the cast results will be compared.

This issue only occurs if at least one of the operands of the comparison is a variable.

```beef
enum MyEnum
{
	Case1,
	Case2,
	Case3
}

enum MyOtherEnum
{
	case One;
	case Two;
	case Three;

	public static explicit operator MyEnum(Self self)
	{
		Debug.WriteLine("Casting to MyEnum");
		return .Case1;
	}
}

class Program
{
	static int Main(String[] args)
	{
		MyOtherEnum myEnum = .One;
		if (myEnum == .Two)
		{
			Debug.WriteLine("We shouldn't be here");
		}
		return 0;
	}
}
```

**Comment by bfiete** [comment]
Fixed at 5267e18783c9f280431de7b691edb7e138a46586

**Comment by aharabada** [comment]
The commit breaks explicit casting between enums.
For example `MyEnum converted = (MyEnum)myEnum;` doesn't use the overloaded operator anymore.

**Comment by bfiete** [comment]
Fixed now at 7c6bdeffbe5344271a53bcd07b275e9d363c6682

**Comment by aharabada** [comment]
It doesn't seem to be fixed. It's still not calling the overloaded operator.

Also this test you wrote to, I assume, test the overloaded explicit cast doesn't actually test whether or not the overloaded cast is used, because overloaded and default cast have the same result for `MyOtherEnum.One`
 https://github.com/beefytech/Beef/blob/7c6bdeffbe5344271a53bcd07b275e9d363c6682/IDEHelper/Tests/src/Operators.bf#L575-L577

**Comment by bfiete** [comment]
Yeah, that was a bad test. I believe this is actually fixed now at 633424b6da47c961e9e5a7139951dd138dc42045

**Comment by aharabada** [comment]
That case works now. However the commit introduced a new bug.
```beef
int32 i = (int32)moe;
Test.Assert(i == 0);

uint32 u = (uint32)moe;
Test.Assert(u == 0);
```
In the Operators.bf file: When you cast to `int32` it works as expected, however casting to `uint32` uses the overload operator thus convertig it to `MyEnum` first.
Consequently something like `(MyEnum)(uint32)moe` has a different result that `(MyEnum)(int32)moe`.

**Comment by bfiete** [comment]
100% for sure this is all fixed now at 0de32f7b3413ffd2f26f0402abb3dae18c9ce84c
