### ISSUE TITLE
Unassigned variable is usable in a specific context

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1430]
While trying to fix an IDE crash that I encountered (https://github.com/beefytech/Beef/pull/1429), I found that Beef currently allows an unassigned variable to be used if that variable is preceded with an enum union matching, which was causing the aforementioned issue.

Example code:
```
		public static Result<int64> Test64()
		{
			return .Err;
		}

		public static int Main(String[] args)
		{
			int64 i64;

			if (Test64() case .Ok(out i64))
			{
			}

			Console.WriteLine(i64); // no error
			return 0;
		}
```

**Comment by disarray2077** [comment]
I noticed that this issue was already fixed, but I found two more issues similar to the old one:

Code with comments describing the issues:
```
			Result<String> str()
			{
				return .Err;
			}

			for (int i < 10)
			{
				String s;

#if true // Issue 1
				// This shouldn't fix the unassigned error
				if (str() case .Ok(out s) || s == null) // s shouldn't be usable after enum matching failed
				{
					Console.WriteLine(s);
					continue;
				}
#endif

#if false // Issue 2
				// This shouldn't cause the unassigned error in Console.WriteLine
				if (true || !(str() case .Ok(out s)))
				{
					continue;
				}
#endif
	
				Console.WriteLine(s);
			}
```

**Comment by kallisto56** [comment]
On latest nightly (https://github.com/beefytech/Beef/commit/b4cfc119a7ee6d108045f77d0f63776fb2a539cf) this is still an issue.
First case with `Int64` works fine and gives an error:
```
ERROR: Use of unassigned local variable 'i64'
```
Second case fails. For convenience, I've attached a project that is ready for testing: [bug.1430.zip](https://github.com/user-attachments/files/18519377/bug.1430.zip)
