### ISSUE TITLE
Object extension fields can get corrupted

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1448]
I'm not sure how to create a small reproducible example of this issue but looks like you can reproduce it in the IDE project, to do so just add this code at the start of `IDEApp.bf`:
```
namespace System
{
	extension Object
	{
#if BF_ENABLE_REALTIME_LEAK_CHECK
		Object mDeleteSentinel ~ { if (Compiler.IsComptime) return; Internal.Dbg_MarkObjectDeleted(_ = new .()); }
#endif
	}
}
```

After that go to line 574 and add a `delete mDebugger;` after `mDebugger = new DebugManager();`, then run the IDE in Debug config, you will find out that `mDeleteSentinel.AllocStackTrace` is corrupted:
![image](https://user-images.githubusercontent.com/86157825/153945769-92266243-5cca-4f53-a512-9d03ecfffd9a.png)

The same doesn't happen if you add the `mDeleteSentinel` field directly to `DebugManager`.

**Comment by bfiete** [comment]
I fixed at issue at 6af0f111c0a3167830e5a3e29c3624fa143ad9de where fields in Object extensions wouldn't get zeroed-out on allocation. After the object is deleted then it should have gotten initialized, though, so I'm not 100% sure this actually fixes your issue.

I tried this out on the IDE codebase and all the objects I inspected had non-corrupted mDeleteSentinel values... so I'll let you tell me if there's still an issue or not.

**Comment by disarray2077** [comment]
Unfortunately the issue wasn't fixed.

I almost thought this was something caused by some crash fixes that I did, but I just tested and this also happens with the nightly from 02/11/2022 (the one that I have installed):
![image](https://user-images.githubusercontent.com/86157825/154154476-820a0da2-7dc3-4236-97cf-eeee5c2108cf.png)

Did you try exactly what I said? Did you have an error at the same point where I show in the screenshot?

**Comment by disarray2077** [comment]
Ok, I just tried to compile without the changes I mentioned and the issue didn't go away.
I was kinda expecting this since I already had this issue for quite some time, but in my project it usually manifests itself by `mDeleteSentinel.AllocStackTrace` containing an `AllocStackTrace` of another unrelated object.

**Comment by disarray2077** [comment]
I put a data breakpoint in `mDeleteSentinel.mDebugAllocInfo` and `mDeleteSentinel.mClassVData` right after `mDebugger` was deleted, maybe this can help, here is the results:

<details>
<summary>mDebugAllocInfo Hit</summary>

![image](https://user-images.githubusercontent.com/86157825/154159903-8fdd2fb0-1bd0-4849-96a7-668390ddb5e4.png)
</details>

<details>
<summary>mClassVData Hit</summary>

![image](https://user-images.githubusercontent.com/86157825/154159941-03814e20-0fe0-4ec5-afb5-2552b03427d9.png)
</details>

These were the only hits before reaching the "Attempted to access deleted object" error.

**Comment by bfiete** [comment]
Ah, yeah- I didn't read the initial instructions closely enough. It did end up being a GC-related issue, as your found -- we omitted System.Object from the GC marking phase because we "knew" it never had objects to mark -- a faulty assumption if it has extensions. Fix incoming tomorrow.

**Comment by bfiete** [comment]
Fixed at b0f019fdd377b3645649ce06511017a22edf0381 / df4f58f586c193d33c85f4f7a0af9d98f50cfe32
