### ISSUE TITLE
Comptime crash

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1464]
The IDE (Nightly 02/20/2022) crashes when I do changes in my code.

[ideCrash.zip](https://github.com/beefytech/Beef/files/8110523/ideCrash.zip)

I'm not quite sure when exactly it crashes, but if the crashdump isn't enough I can try to find steps to reproduce it.

**Comment by bfiete** [comment]
I have a potential fix committed, but I can't test it obviously...

**Comment by aharabada** [comment]
Oh, I mailed the code to beef@beefytech.com as it was too large for github. I thought I had written a comment for that. Apparently not, sorry for that.

It's also not fixed

**Comment by bfiete** [comment]
Hm. You build from source after I made that comment and it still doesn't work? I've been trying to repro with the instructions in the email but haven't been able to get anything yet...

**Comment by bfiete** [comment]
If you're just trying the latest nightly - this commit isn't in there yet.

**Comment by aharabada** [comment]
Yes, I build from source and it still happens. Though I think that it happens a lot less frequent with the latest commits. Did you manage to reproduce it without the commit? Without it crashes within seconds, with the commit it takes much longer.

![crashGif](https://user-images.githubusercontent.com/16611882/155574297-67d46d9c-05e8-485a-b015-e6c3201883ef.gif)

**Comment by bfiete** [comment]
I was able to get this other failure (I could only get it in release mode). I committed another fix at faaae112b5f115c3330e0420f14d488505efc283 and I can't get a failure anymore. Try it out?

**Comment by aharabada** [comment]
Still crashes for me. I believe it crashes more reliable when I clean from time to time, could be coincidence though.

**Comment by bfiete** [comment]
Can you send a new crash dump from the last nightly build?

**Comment by bfiete** [comment]
Also- were you getting a crash from these exact repro instructions, or just during other normal programming?

**Comment by aharabada** [comment]
I'm getting the crash with the repro instructions.

Crashdump from the 2/25/2022 nighly: [ideCrash.zip](https://github.com/beefytech/Beef/files/8146920/ideCrash.zip)

**Comment by bfiete** [comment]
I still wasn't able to reproduce it, but the crash dump was helpful and I believe db8a1b63675205ba8108d298694170b1136bac31 should fix that.
