### ISSUE TITLE
Comptime emit view isn't available if the method is only called through a interface

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1550]
Ok, this time I'm sure I found the emit view issue that I'm having in my code \=P
(This is the issue that I really meant to report in https://github.com/beefytech/Beef/issues/1539)

Example code:
```cs
	class TestEmit<T, C>
		where C : const String
	{
		[Comptime]
		public static void EmitTest()
		{
			if (typeof(T).IsGenericParam)
				return;
			Compiler.MixinRoot("NOP!();");
		}

		public void Test()
		{
			EmitTest(); // "Emit" doesn't show up
		}
	}

	class Program
	{
		public static TestEmit<Self, C> TestTestEmit<C>(C c)
				where C : const String
		{
			return new TestEmit<Self, C>();
		}

		public static int Main(String[] args)
		{
			TestTestEmit("oi");
		}
	}
```
Tested with https://github.com/beefytech/Beef/commit/e852ba49bb7195c18f51d6b8e944048886765114

**Comment by bfiete** [comment]
This is by design - methods in specialized generic classes aren't generated unless they are actually called.

If you change `return new TestEmit<Self, C>();` to `return new TestEmit<Self, C>()..Test();` then you will get an Emit marker where you expect it.

**Comment by disarray2077** [comment]
Oh, I see. Now that you mentioned it, I noticed that my class implements an interface, and its methods are only called through that said interface, but looks like beef doesn't recognize that. As an example, the call doesn't show up in "Find All References":
![image](https://user-images.githubusercontent.com/86157825/165842708-edb121e6-f6f0-4bca-9625-0e9d461df71c.png)

And if I change the code to:
```cs
	interface ITestEmit
	{
		void Test();
	}

	public class TestEmit<T, C> : ITestEmit
		where C : const String
	{
		[Comptime]
		public static void EmitTest()
		{
			if (typeof(T).IsGenericParam)
				return;
			Compiler.MixinRoot("NOP!();");
		}

		public void Test()
		{
			EmitTest(); // "Emit" doesn't show up
		}
	}

	class Program
	{
		public static TestEmit<Self, C> TestTestEmit<C>(C c)
				where C : const String
		{
			return new TestEmit<Self, C>();
		}

		public static int Main(String[] args)
		{
			ITestEmit t = TestTestEmit("oi");
			t.Test();
		}
	}
```

The emit marker doesn't show up, even though it shows up if I use `let` instead of `ITestEmit`.

**Comment by bfiete** [comment]
Fixed at 1bacf5eee27457e143ce713ac30732a46b8b4677

It was actually a wider issue where some methods that would be generated in a full compile weren't being generated from the IDE.

**Comment by disarray2077** [comment]
Hm... This did solve the issue in the test code and also in the (now old) version of my project code that I had sent to you, but the Emit marker still doesn't show up in the current version...
![image](https://user-images.githubusercontent.com/86157825/166116597-40c5c80e-c0e9-4ce4-950b-ffac7f1f7fa3.png)

I guess I will just share the project with you again.
