### ISSUE TITLE
[Bug] Result<T> not working with namespace

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1618]
In the latest nightly, using full namespace on `Result<T>` now fails: `Too few generic parameters, expected 1 more`.

Example:
```beef
class Program
{
    public static int Main()
    {
        System.Result<void> a;
        return 0;
    }
}
```

**Comment by bfiete** [comment]
Fixed at 8aa58b3804239514cab4f44be4dec0ed0bc189cc

**Comment by m910q** [comment]
The issue is still there.
Did you commit something else by mistake? The commit looks to only be for some testing.

**Comment by bfiete** [comment]
Yeah, I did. Actual fix at fa0f559537dfc1c64deae37f9b5e126f4364450c
