### ISSUE TITLE
[Enhancement] Way to check wether a specific library exists/is depended in the current workspace

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2040]
As discussed in the discord, the idea is to be able to effectivly have optional dependencies.
This should probably be handled through the preprocessor
such as 
`#if depends("raylib")`

**Comment by bfiete** [comment]
I implemented this but simpler. BF_DEPENDS_xxx
IE: `#if BF_DEPENDS_RAYLIB`

**Comment by Booklordofthedings** [comment]
There is still an issue here with library names that contain a "-"

**Comment by bfiete** [comment]
'-' issue fixed at b9d0dc693fdd3bad7183ad6aeae0cdb3cecfa6a7
