### ISSUE TITLE
Method matching issue causing ambiguous method call error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#2102]
The following code fails to compile because of an ambiguous method call error in the `TestClass.CallTest` method. However, uncommenting the alternate overload (`public static mixin Test(Type value)`) allows the code to compile successfully, and this seems to make no sense.

```bf
using System;
using System.Collections;

namespace simple_test;

class Program
{
    public static mixin Test<T>(T a) where T : struct {}
    // The code compiles if you uncomment this line.
    //public static mixin Test(Type value) {}
    public static mixin Test<T>(T a) where T : class, delete {}

    public class TestClass<TValue>
    {
        public bool CallTest(TValue val)
            where TValue : var
        {
            Program.Test!(val); // ERROR: Ambiguous method call for 'Test'
            return true;
        }
    }

    static void Main()
    {
        let test = scope TestClass<int>();
        test.CallTest(2);
    }
}
```

In addition to that, if the `CallTest` method contains any generic parameters, the compiling fails even if the `Test(Type value)` overload is present:

```bf
using System;
using System.Collections;

namespace simple_test;

class Program
{
	public static mixin Test<T>(T a) where T : struct {}
	public static mixin Test(Type value) {}
	public static mixin Test<T>(T a) where T : class, delete {}

	public class TestClass<TValue>
	{
		public bool CallTest<T>(TValue val)
			where TValue : var
		{
			Program.Test!(val); // ERROR: Ambiguous method call for 'Test'
			return true;
		}
	}

	static void Main ()
	{
		let test = scope TestClass<int>();
		test.CallTest<int>(2);
	}
}
```

Tested with: https://github.com/beefytech/Beef/commit/7b29a4facb656eb5d6a87526e2b8a60b2128be42

**Comment by bfiete** [comment]
When there are multiple matching mixins available, the compiler has rules for which ones are "best". Between the two generic ones, there is no "better" mixin so it's ambiguous. 

If these were the two generic methods available:
```C#
public static mixin Test<T>(T a) where T : struct {}
public static mixin Test<T>(T a) where T : struct, IDisposable {}
```
... then the second one will be chosen because it is "better", given that it's constraints are a superset of the first method.

And the `public static mixin Test(Type value) {}` mixin gets chosen because non-generic is "better" than generic.

But anyway, the compiler should just be made to not complain about ambiguity when you have a 'var' constraint.

**Comment by bfiete** [comment]
Fixed at 2d74aac74c47725fd6cc098523345e1aef15062a

**Comment by disarray2077** [comment]
@bfiete In the latest Beef compiled from source, the second issue regarding the generic CallTest method is still occurring:
```bf
ERROR: Ambiguous method call for 'Test'
  while specializing type 'simple_test.Program.TestClass<int>' at line 17:12 in d:\BeefLang\simple_test\src\bug3.bf
   Program.Test!(val); // ERROR: Ambiguous method call for 'Test'
           ^^^^^
  > 'simple_test.Program.Test!<int>(int a)' is a candidate at line 10:22 in d:\BeefLang\simple_test\src\bug3.bf
  public static mixin Test<T>(T a) where T : class, delete {}
                      ^^^^
  > 'simple_test.Program.Test!<int>(int a)' is a candidate at line 8:22 in d:\BeefLang\simple_test\src\bug3.bf
  public static mixin Test<T>(T a) where T : struct {}
                      ^^^^
```

**Comment by bfiete** [comment]
Oops, I thought had gotten that one too. Now fixed at fd24ab21af816f45d5892c3813f5576f5bdf7468
