### ISSUE TITLE
0.42.5 - IDE Crash

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#322]
If you paste `Dictionary<K, V>` upon `(TKey key, TValue value)`, the IDE crashes.

```
using System;
using System.Collections;

namespace test3
{
	class TestTest
	{
		typealias KeyValuePair<TKey, TValue> = (TKey key, TValue value);

		public static bool Test<K, V>(Dictionary<K, V> obj) where K : IHashable
		{
			if (obj == null)
				return NonexistentFunc((IEnumerator<KeyValuePair<K, V>>)null);
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/6fe9c78adab7dbea94e06fc037601ad7d63ec5c9

**Comment by Igoorx** [comment]
@bfiete If I'm not wrong, you have already updated the Nightly build, right? Because this crash still is happening, tested in the build 0.42.5 (Nightly 06/04/2020)

**Comment by bfiete** [comment]
Actually there's an issue with the build clock... these builds weren't actually being built at 10PM as they were supposed to, and this build occurred before the fix checkin...

**Comment by bfiete** [comment]
The build trigger was on UTC so it was building at 3PM. There will be another build in 5.5 hours with these actual changes -- ALSO tagged with today's date.

**Comment by Igoorx** [comment]
> The build trigger was on UTC so it was building at 3PM. There will be another build in 5.5 hours with these actual changes -- ALSO tagged with today's date.

@bfiete The crash still is happening, now for sure
![image](https://user-images.githubusercontent.com/14041768/83973715-a264f780-a8be-11ea-8681-9fe2941c4dd0.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f251b6e58e1920029c70d8a9df2dfbf516d95f61 (again)
