### ISSUE TITLE
Possible issue passing struct to extern DLL

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#74]
```
[Import("allegro-5.2.dll"), CLink]
public static extern void al_clear_to_color(ALLEGRO_COLOR color);

[CRepr]
public struct ALLEGRO_COLOR
{
    public float r, g, b, a;
}
```

When drawing a color to the screen such as RGB(1.0f, 0, 0), it is displaying RGB(0, 1.0f, 0).
Checked the struct in the debugger and the fields are all assigned correctly and assuming i'm linking to the dll correctly (which i think so, all other methods so far are working) possibly a codegen issue?

**Comment by bfiete** [comment]
Is this for a 32-bit or 64-bit build?

**Comment by damianday** [comment]
That's for 32 bit I'll try and create s reduced test case if that will help

**Comment by bfiete** [comment]
I do see there's a lowering issue for Win32 by-value struct arguments. Diving in still.

**Comment by bfiete** [comment]
This should be fixed by https://github.com/beefytech/Beef/commit/686050a68bdb9b6abc9ebb4092cd7221831e3f9f. I should build a comprehensive test suite for this kind of C interop stuff...

**Comment by damianday** [comment]
```
[Import(AllegroDllName), CLink]
public static extern ALLEGRO_COLOR al_map_rgba(uint8 r, uint8 g, uint8 b, uint8 a);

public struct Color
	{
	    private uint8 _r = 0;
	    private uint8 _g = 0;
	    private uint8 _b = 0;
	    private uint8 _a = 0;
	    
	    public this(uint8 r, uint8 g, uint8 b, uint8 a)
	    {
	        _r = r;
	        _g = g;
	        _b = b;
	        _a = a;
	    }
	    
	    public this(uint8 r, uint8 g, uint8 b)
	    {
	        this = Color(r, g, b, 255);
	    }

	    public uint8 R
	    {
	        get { return _r; }
	    }
	    
	    public uint8 G
	    {
	        get { return _g; }
	    }
	    
	    public uint8 B
	    {
	        get { return _b; }
	    }
	    
	    public uint8 A
	    {
	        get { return _a; }
	  }
}

public void Clear(Color color)
{
	let c = AllegroAPI.al_map_rgba(color.R, color.G, color.B, color.A);
}
```

Now getting asertion failed
val->GetType()->IsPointer()


[crash.zip](https://github.com/beefytech/Beef/files/4320476/crash.zip)

**Comment by damianday** [comment]
Attached screenshot of the debug output.
(On a side note would be useful if i could copy the lines from the call stack window)
![screenshot](https://user-images.githubusercontent.com/1334173/76458644-bd64c000-63d2-11ea-8ae2-4c6089cbc568.png)

**Comment by bfiete** [comment]
This should be fixed with this https://github.com/beefytech/Beef/commit/7a08e7bf111cf5f23c2097964660bc4c308cb9d1

**Comment by damianday** [comment]
Unfortunately still throwing an assert. I've attached a reduced test project. It does not throw when compiled in 64 bit only 32 bit.
[Test.zip](https://github.com/beefytech/Beef/files/4321575/Test.zip)

**Comment by bfiete** [comment]
That was actually a different bug from the original. But it should be fixed now with https://github.com/beefytech/Beef/commit/5276bd4533e92f23b734a211a6cadbb972cf0a9e

**Comment by damianday** [comment]
Excellent! Working great now thanks
