### ISSUE TITLE
[BUG] Linq crash on test

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#862]
https://github.com/xposure/Beef.Linq/commit/b84579da8137516ac9862a66ef772013c28fd98f

**Comment by xposure** [comment]
f2ab799 
this one is stopping me from really doing anything.

There is quite a labyrinth of generics in beef.linq now and it has reallllly made the IDE unstable, I probably had over 50 crashes today and they are all related to generics, but I think these two commits are the bulk of the crashes.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/cd882b09a561ca9a4b4b13866b8b77434202d932

**Comment by xposure** [comment]
f2ab799

Still seems to crash when loading the project.

**Comment by xposure** [comment]
So this crash that still persists is from debug mode of the IDE at this location

```
#if _DEBUG
				if (type->IsGenericTypeInstance())
				{
					// We can't contain deleted generic arguments without being deleted ourselves
					BfTypeInstance* genericType = (BfTypeInstance*)type;

					for (auto genericTypeArg : genericType->mGenericTypeInfo->mTypeGenericArguments)
					{
						BF_ASSERT((!genericTypeArg->IsDeleting()));
					}
				}
#endif
```

Additionally I opened the project in the release IDE and it worked for a moment, then I hit goto definition on the follow code and got this error.

![image](https://user-images.githubusercontent.com/6292318/106024127-74266900-6095-11eb-8938-d895f791c532.png)


This came from the end of the file BfModuleTypeUtils

```
	else if (resolvedType->IsConstExprValue())
	{
		auto constExprValueType = (BfConstExprValueType*)resolvedType;
		str += "const ";
		 		
		DoTypeToString(str, constExprValueType->mType, typeNameFlags, genericMethodNameOverrides);
		str += " ";

		VariantToString(str, constExprValueType->mValue);
		
		return;
	}
	BFMODULE_FATAL(this, "Not implemented");
	str += "???";
	return;
```

**Comment by bfiete** [comment]
Ah yeah I only fixed the initial bug, I didn't see you added on to this with 'f2ab799'.

**Comment by bfiete** [comment]
I was right, it was an issue with type aliases.
https://github.com/beefytech/Beef/commit/b9593348c727ca1f64220c5a3566b0d08a7e8b40

**Comment by xposure** [comment]
![image](https://user-images.githubusercontent.com/6292318/106185160-75789400-6170-11eb-8209-1a090eac1fe1.png)

Still got it with the latest code from today.

**Comment by bfiete** [comment]
That doesn't look like the same thing, but we can leave it under here anyway.

**Comment by bfiete** [comment]
Is there a version hash to go with this bug?

**Comment by xposure** [comment]
Latest code from today.

**Comment by xposure** [comment]
![image](https://user-images.githubusercontent.com/6292318/106232145-43dbe900-61c1-11eb-90a7-f1ec16bc6e83.png)
 Heres another one that isn't typealias

**Comment by bfiete** [comment]
Can you let me know if you're still seeing this with the latest fixes?

**Comment by xposure** [comment]
We can close it and ill open a new one if it happens again.
