### ISSUE TITLE
[Bug] ??= Operator doesn't work

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#937]
The ??= operator doesn't work. The following example will throw the error "Operator '??' cannot be applied to operands of type 'System.String'"

```beef
String str = "Hello";
String str2 = null;
str2 ??= str;
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4575c6413356bca3ec1a08fc6be81e226b86eb48

**Comment by aharabada** [comment]
Just compiled and tested it. It's not fixed (not entirely at least). When testing the example str2 remains null eventough it should become "Hello".

**Comment by RogueMacro** [comment]
It shouldn't be in the latest nightly yet though, right? It be compiled in about 12-14 hours or something like that, if I'm not mistaken?

**Comment by aharabada** [comment]
I know, I compiled it myself

**Comment by bfiete** [comment]
Actually for sure fixed this time https://github.com/beefytech/Beef/commit/97283b3113475d40279a9b8e284fc9def4aad77d
